import Head from 'next/head';
import {
  Container,
  Content,
  H1,
  P1,
  P2,
  P3,
} from '../../../components/styled/SupportElements';
const support = () => {
  return (
    <>
      <Head>
        <title>ponzi | support</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Customer Support</H1>
            <P1>
              Here at ponzi, we are here for you along <em>almost</em> the
              entire process. We want to make sure taking your money is a very
              seamless process for you.
            </P1>
            <P2>
              If you need help setting up a deposit, or would like to discuss
              investment options, please contact your representative.
            </P2>
            <P3>
              If you need help with any other issues, including trying to
              withdraw funds, please do not contact us.
            </P3>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default support;
