import Head from 'next/head';
import {
  Container,
  Content,
  H1,
  P1,
  P2,
  P3,
} from '../../../components/styled/ImpactElements';
const impact = () => {
  return (
    <>
      <Head>
        <title>ponzi | social impact</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Shaping a world we want to live in</H1>
            <P1>
              We’re in a privileged position. We have the influence to make a
              real impact. And we’re using it to shape a better future for
              society.
            </P1>
            <P2>
              As a global brand, we impact the world, our industry, and our
              listeners every single day. And influence comes with
              responsibility. We’re choosing to show up for society, act with
              purpose and use our platform for good. We want to help shape a
              world that is welcoming for people of all backgrounds and
              identities, that centers justice and equity in everything we do
              and brings wellness and joy to all.
            </P2>
            <P3>
              Our platform is powerful, and we’re using it to amplify the
              voices, stories and cultures of marginalized and underrepresented
              communities around the world.
            </P3>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default impact;
