import Head from 'next/head';
import { Container, Content, H1, H2, P1, P2, P3 } from './TosElements';
const tos = () => {
  return (
    <>
      <Head>
        <title>ponzi | terms</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Terms of Service</H1>

            <H2>Introduction</H2>

            <P1>
              These Website Standard Terms and Conditions written on this
              webpage shall manage your use of our website, ponzi accessible at
              ponzi.com.
            </P1>

            <P1>
              These Terms will be applied fully and affect to your use of this
              Website. By using this Website, you agreed to accept all terms and
              conditions written in here. You must not use this Website if you
              disagree with any of these Website Standard Terms and Conditions.
            </P1>

            <P1>
              Minors or people below 18 years old are not allowed to use this
              Website.
            </P1>

            <H2>Intellectual Property Rights</H2>

            <P1>
              Other than the content you own, under these Terms, ponzi and/or
              its licensors own all the intellectual property rights and
              materials contained in this Website.
            </P1>

            <P1>
              You are granted limited license only for purposes of viewing the
              material contained on this Website.
            </P1>

            <H2>Restrictions</H2>

            <P1>
              Certain areas of this Website are restricted from being access by
              you and ponzi may further restrict access by you to any areas of
              this Website, at any time, in absolute discretion. Any user ID and
              password you may have for this Website are confidential and you
              must maintain confidentiality as well.
            </P1>

            <H2>Your Content</H2>

            <P1>
              In these Website Standard Terms and Conditions, {'"'}Your Content
              {'"'}
              shall mean any audio, video text, images or other material you
              choose to display on this Website. By displaying Your Content, you
              grant ponzi a non-exclusive, worldwide irrevocable, sub licensable
              license to use, reproduce, adapt, publish, translate and
              distribute it in any and all media.
            </P1>

            <P1>
              Your Content must be your own and must not be invading any
              third-party&apos;s rights. ponzi reserves the right to remove any
              of Your Content from this Website at any time without notice.
            </P1>

            <H2>Your Privacy</H2>

            <P1>Please read Privacy Policy.</P1>

            <H2>No warranties</H2>

            <P1>
              This Website is provided "as is," with all faults, and ponzi
              express no representations or warranties, of any kind related to
              this Website or the materials contained on this Website. Also,
              nothing contained on this Website shall be interpreted as advising
              you.
            </P1>

            <H2>Limitation of liability</H2>

            <P1>
              In no event shall ponzi, nor any of its officers, directors and
              employees, shall be held liable for anything arising out of or in
              any way connected with your use of this Website whether such
              liability is under contract.  ponzi, including its officers,
              directors and employees shall not be held liable for any indirect,
              consequential or special liability arising out of or in any way
              related to your use of this Website.
            </P1>

            <H2>Indemnification</H2>

            <P1>
              You hereby indemnify to the fullest extent ponzi from and against
              any and/or all liabilities, costs, demands, causes of action,
              damages and expenses arising in any way related to your breach of
              any of the provisions of these Terms.
            </P1>

            <H2>Severability</H2>

            <P1>
              If any provision of these Terms is found to be invalid under any
              applicable law, such provisions shall be deleted without affecting
              the remaining provisions herein.
            </P1>

            <H2>Variation of Terms</H2>

            <P1>
              ponzi is permitted to revise these Terms at any time as it sees
              fit, and by using this Website you are expected to review these
              Terms on a regular basis.
            </P1>

            <H2>Assignment</H2>

            <P1>
              The ponzi is allowed to assign, transfer, and subcontract its
              rights and/or obligations under these Terms without any
              notification. However, you are not allowed to assign, transfer, or
              subcontract any of your rights and/or obligations under these
              Terms.
            </P1>

            <H2>Entire Agreement</H2>

            <P1>
              These Terms constitute the entire agreement between ponzi and you
              in relation to your use of this Website, and supersede all prior
              agreements and understandings.
            </P1>

            <H2>Governing Law & Jurisdiction</H2>

            <P1>
              These Terms will be governed by and interpreted in accordance with
              the laws of the State of af, and you submit to the non-exclusive
              jurisdiction of the state and federal courts located in af for the
              resolution of any disputes.
            </P1>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default tos;
