import Head from 'next/head';
import { Container, Content, H1 } from './DashboardElements';

const signin = () => {
  return (
    <>
      <Head>
        <title>ponzi | dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>User dashboard coming soon!</H1>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default signin;
