import Head from 'next/head';
import Hero from '../components/hero';
import About from '../components/about';
import Discover from '../components/discover';
import Services from '../components/services';

export default function Home() {
  return (
    <>
      <Head>
        <title>ponzi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Hero />
        <About />
        <Discover />
        <Services />
      </main>
    </>
  );
}
