import Head from 'next/head';
import {
  Container,
  Content,
  H1,
  P1,
  P2,
  P3,
} from '../../../components/styled/OpeningsElements';
const openings = () => {
  return (
    <>
      <Head>
        <title>ponzi | openings</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Current Openings</H1>
            <P1>
              Why would you want to work here? Well, what is more fun than
              taking someone&apos;s money?
            </P1>
            <P2>
              Currently, we do not have any open positions. Keep an eye on this
              page and our social channels for any news regarding future
              positions.
            </P2>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default openings;
