import Head from 'next/head';
import { Container, Content, H1, P1, P2, P3 } from './AmbassadorsElements';
const ambassadors = () => {
  return (
    <>
      <Head>
        <title>ponzi | ambassadors</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Join our Ambassador Program</H1>
            <P1>
              Did you go viral on Tiktok? Have thousands of raving fans on your
              Twitch channel? Do you post daily VLOGs on Youtube?
            </P1>
            <P2>
              If so, you sound like a perfect fit for ponzi's Ambassador
              Program. We offer you almost no benefits that we do not offer our
              regular customers, and in return, we constantly hound you about
              giving us shout outs online.
            </P2>
            <P3>
              Let us take advantage of your fame! Apply today with your
              representative.
            </P3>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default ambassadors;
