import Head from 'next/head';
import { Container, Content, H1, P1, P2, P3 } from './PressElements';
const press = () => {
  return (
    <>
      <Head>
        <title>ponzi | press</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Public Relations</H1>
            <P1>
              Here at ponzi we are not fans of {'"'}reporting{'"'} or {'"'}facts
              {'"'}.
            </P1>
            <P2>
              We don&apos;t think it is in our best interest to discuss our
              business with the media and our lawyer highly advised against it
              before he quit and left the country.
            </P2>
            <P3>
              Honestly, we just want to wish you good look with getting in touch
              with anyone who represents this company. You seriously have your
              work cut out for you.
            </P3>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default press;
