import Head from 'next/head';
import {
  Container,
  Content,
  H1,
  P1,
  P2,
  P3,
} from '../../../components/styled/InvestorsElements';
const investors = () => {
  return (
    <>
      <Head>
        <title>ponzi | investors</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <Content>
            <H1>Invest in us</H1>
            <P1>
              At ponzi, we know how easily a fool and his money are separated.
              Why stop at giving us some of your money, when you can hand it all
              over?
            </P1>
            <P2>
              On top of {'"'}investing{'"'} your hard earned money in our
              Standard Fund, we also offer opportunities for especially easy
              marks to invest further in our company.
            </P2>
            <P3>
              If you are interested in funding our organization, mention
              investment opportunities to your representative.
            </P3>
          </Content>
        </Container>
      </main>
    </>
  );
};

export default investors;
